### ISSUE TITLE
1个bug1个建议

### ISSUE THREAD

**Issue by telangpu** [preflower/vscode-translation#4]
1、bug
当选中某个单词后，鼠标放到了其他单词上，会弹出选中部分的翻译。

2、建议
因为鼠标放到了某些语法单词上，可能由于其他扩展，会弹出相关的语法提示，而不是翻译。可否增加一个功能控制，指定弹出的是翻译

**Comment by preflower** [comment]
第一个问题是希望鼠标只悬浮于选中字段才触发翻译？

第二点无法做到，多个插件触发悬停提示 vscode会自动合并，无法由插件控制
